services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - task-manager-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/tasks"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - task-manager-network
    environment:
      - REACT_APP_API_URL=http://localhost:8080

networks:
  task-manager-network:
    driver: bridge
